// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pages.sql

package postgresdb

import (
	"context"
)

const consumeE2EESelfDestructPage = `-- name: ConsumeE2EESelfDestructPage :one
DELETE FROM pages
WHERE title = $1 AND self_destruct = TRUE AND locked = FALSE AND end_to_end_encrypted = TRUE
RETURNING title, text, cursor_start, cursor_end, published, self_destruct, locked, lock_salt, lock_verifier, end_to_end_encrypted, e2ee_auth_hash
`

type ConsumeE2EESelfDestructPageRow struct {
	Title             string
	Text              string
	CursorStart       int64
	CursorEnd         int64
	Published         bool
	SelfDestruct      bool
	Locked            bool
	LockSalt          string
	LockVerifier      string
	EndToEndEncrypted bool
	E2eeAuthHash      string
}

func (q *Queries) ConsumeE2EESelfDestructPage(ctx context.Context, title string) (ConsumeE2EESelfDestructPageRow, error) {
	row := q.db.QueryRowContext(ctx, consumeE2EESelfDestructPage, title)
	var i ConsumeE2EESelfDestructPageRow
	err := row.Scan(
		&i.Title,
		&i.Text,
		&i.CursorStart,
		&i.CursorEnd,
		&i.Published,
		&i.SelfDestruct,
		&i.Locked,
		&i.LockSalt,
		&i.LockVerifier,
		&i.EndToEndEncrypted,
		&i.E2eeAuthHash,
	)
	return i, err
}

const consumeSelfDestructPage = `-- name: ConsumeSelfDestructPage :one
DELETE FROM pages
WHERE title = $1 AND self_destruct = TRUE AND locked = FALSE AND end_to_end_encrypted = FALSE
RETURNING title, text, cursor_start, cursor_end, published, self_destruct, locked, lock_salt, lock_verifier, end_to_end_encrypted, e2ee_auth_hash
`

type ConsumeSelfDestructPageRow struct {
	Title             string
	Text              string
	CursorStart       int64
	CursorEnd         int64
	Published         bool
	SelfDestruct      bool
	Locked            bool
	LockSalt          string
	LockVerifier      string
	EndToEndEncrypted bool
	E2eeAuthHash      string
}

func (q *Queries) ConsumeSelfDestructPage(ctx context.Context, title string) (ConsumeSelfDestructPageRow, error) {
	row := q.db.QueryRowContext(ctx, consumeSelfDestructPage, title)
	var i ConsumeSelfDestructPageRow
	err := row.Scan(
		&i.Title,
		&i.Text,
		&i.CursorStart,
		&i.CursorEnd,
		&i.Published,
		&i.SelfDestruct,
		&i.Locked,
		&i.LockSalt,
		&i.LockVerifier,
		&i.EndToEndEncrypted,
		&i.E2eeAuthHash,
	)
	return i, err
}

const convertPageToE2EE = `-- name: ConvertPageToE2EE :execrows
UPDATE pages
SET text = $2,
    cursor_start = $3,
    cursor_end = $4,
    published = FALSE,
    end_to_end_encrypted = TRUE,
    e2ee_auth_hash = $5,
    updated_at = CURRENT_TIMESTAMP
WHERE title = $1
  AND end_to_end_encrypted = FALSE
  AND locked = FALSE
  AND self_destruct = FALSE
`

type ConvertPageToE2EEParams struct {
	Title        string
	Text         string
	CursorStart  int64
	CursorEnd    int64
	E2eeAuthHash string
}

func (q *Queries) ConvertPageToE2EE(ctx context.Context, arg ConvertPageToE2EEParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, convertPageToE2EE,
		arg.Title,
		arg.Text,
		arg.CursorStart,
		arg.CursorEnd,
		arg.E2eeAuthHash,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createPage = `-- name: CreatePage :execrows
INSERT INTO pages (
    title,
    text,
    cursor_start,
    cursor_end,
    published,
    self_destruct,
    locked,
    lock_salt,
    lock_verifier,
    end_to_end_encrypted,
    e2ee_auth_hash
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11
)
ON CONFLICT (title) DO NOTHING
`

type CreatePageParams struct {
	Title             string
	Text              string
	CursorStart       int64
	CursorEnd         int64
	Published         bool
	SelfDestruct      bool
	Locked            bool
	LockSalt          string
	LockVerifier      string
	EndToEndEncrypted bool
	E2eeAuthHash      string
}

func (q *Queries) CreatePage(ctx context.Context, arg CreatePageParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createPage,
		arg.Title,
		arg.Text,
		arg.CursorStart,
		arg.CursorEnd,
		arg.Published,
		arg.SelfDestruct,
		arg.Locked,
		arg.LockSalt,
		arg.LockVerifier,
		arg.EndToEndEncrypted,
		arg.E2eeAuthHash,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getPage = `-- name: GetPage :one
SELECT title, text, cursor_start, cursor_end, published, self_destruct, locked, lock_salt, lock_verifier, end_to_end_encrypted, e2ee_auth_hash
FROM pages
WHERE title = $1
LIMIT 1
`

type GetPageRow struct {
	Title             string
	Text              string
	CursorStart       int64
	CursorEnd         int64
	Published         bool
	SelfDestruct      bool
	Locked            bool
	LockSalt          string
	LockVerifier      string
	EndToEndEncrypted bool
	E2eeAuthHash      string
}

func (q *Queries) GetPage(ctx context.Context, title string) (GetPageRow, error) {
	row := q.db.QueryRowContext(ctx, getPage, title)
	var i GetPageRow
	err := row.Scan(
		&i.Title,
		&i.Text,
		&i.CursorStart,
		&i.CursorEnd,
		&i.Published,
		&i.SelfDestruct,
		&i.Locked,
		&i.LockSalt,
		&i.LockVerifier,
		&i.EndToEndEncrypted,
		&i.E2eeAuthHash,
	)
	return i, err
}

const listPublishedPageTitles = `-- name: ListPublishedPageTitles :many
SELECT title
FROM pages
WHERE published = TRUE AND self_destruct = FALSE AND end_to_end_encrypted = FALSE
ORDER BY title
`

func (q *Queries) ListPublishedPageTitles(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listPublishedPageTitles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var title string
		if err := rows.Scan(&title); err != nil {
			return nil, err
		}
		items = append(items, title)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPage = `-- name: UpsertPage :exec
INSERT INTO pages (
    title,
    text,
    cursor_start,
    cursor_end,
    published,
    self_destruct,
    locked,
    lock_salt,
    lock_verifier,
    end_to_end_encrypted,
    e2ee_auth_hash
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11
)
ON CONFLICT (title) DO UPDATE SET
    text = EXCLUDED.text,
    cursor_start = EXCLUDED.cursor_start,
    cursor_end = EXCLUDED.cursor_end,
    published = EXCLUDED.published,
    self_destruct = EXCLUDED.self_destruct,
    locked = EXCLUDED.locked,
    lock_salt = EXCLUDED.lock_salt,
    lock_verifier = EXCLUDED.lock_verifier,
    end_to_end_encrypted = EXCLUDED.end_to_end_encrypted,
    e2ee_auth_hash = EXCLUDED.e2ee_auth_hash,
    updated_at = CURRENT_TIMESTAMP
`

type UpsertPageParams struct {
	Title             string
	Text              string
	CursorStart       int64
	CursorEnd         int64
	Published         bool
	SelfDestruct      bool
	Locked            bool
	LockSalt          string
	LockVerifier      string
	EndToEndEncrypted bool
	E2eeAuthHash      string
}

func (q *Queries) UpsertPage(ctx context.Context, arg UpsertPageParams) error {
	_, err := q.db.ExecContext(ctx, upsertPage,
		arg.Title,
		arg.Text,
		arg.CursorStart,
		arg.CursorEnd,
		arg.Published,
		arg.SelfDestruct,
		arg.Locked,
		arg.LockSalt,
		arg.LockVerifier,
		arg.EndToEndEncrypted,
		arg.E2eeAuthHash,
	)
	return err
}
