// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgresdb

import (
	"context"
)

type Querier interface {
	ConsumeSelfDestructPage(ctx context.Context, title string) (ConsumeSelfDestructPageRow, error)
	CreatePage(ctx context.Context, arg CreatePageParams) (int64, error)
	GetPage(ctx context.Context, title string) (GetPageRow, error)
	ListPublishedPageTitles(ctx context.Context) ([]string, error)
	UpsertPage(ctx context.Context, arg UpsertPageParams) error
}

var _ Querier = (*Queries)(nil)
