CREATE TABLE pages (
    title TEXT PRIMARY KEY,
    text TEXT NOT NULL DEFAULT '',
    cursor_start BIGINT NOT NULL DEFAULT 0,
    cursor_end BIGINT NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
