// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pages.sql

package sqlitedb

import (
	"context"
)

const consumeSelfDestructPage = `-- name: ConsumeSelfDestructPage :one
DELETE FROM pages
WHERE title = ?1 AND self_destruct = TRUE AND locked = FALSE
RETURNING title, text, cursor_start, cursor_end, published, self_destruct, locked, lock_salt, lock_verifier
`

type ConsumeSelfDestructPageRow struct {
	Title        string
	Text         string
	CursorStart  int64
	CursorEnd    int64
	Published    bool
	SelfDestruct bool
	Locked       bool
	LockSalt     string
	LockVerifier string
}

func (q *Queries) ConsumeSelfDestructPage(ctx context.Context, title string) (ConsumeSelfDestructPageRow, error) {
	row := q.db.QueryRowContext(ctx, consumeSelfDestructPage, title)
	var i ConsumeSelfDestructPageRow
	err := row.Scan(
		&i.Title,
		&i.Text,
		&i.CursorStart,
		&i.CursorEnd,
		&i.Published,
		&i.SelfDestruct,
		&i.Locked,
		&i.LockSalt,
		&i.LockVerifier,
	)
	return i, err
}

const createPage = `-- name: CreatePage :execrows
INSERT INTO pages (
    title,
    text,
    cursor_start,
    cursor_end,
    published,
    self_destruct,
    locked,
    lock_salt,
    lock_verifier
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8,
    ?9
)
ON CONFLICT (title) DO NOTHING
`

type CreatePageParams struct {
	Title        string
	Text         string
	CursorStart  int64
	CursorEnd    int64
	Published    bool
	SelfDestruct bool
	Locked       bool
	LockSalt     string
	LockVerifier string
}

func (q *Queries) CreatePage(ctx context.Context, arg CreatePageParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createPage,
		arg.Title,
		arg.Text,
		arg.CursorStart,
		arg.CursorEnd,
		arg.Published,
		arg.SelfDestruct,
		arg.Locked,
		arg.LockSalt,
		arg.LockVerifier,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getPage = `-- name: GetPage :one
SELECT title, text, cursor_start, cursor_end, published, self_destruct, locked, lock_salt, lock_verifier
FROM pages
WHERE title = ?1
LIMIT 1
`

type GetPageRow struct {
	Title        string
	Text         string
	CursorStart  int64
	CursorEnd    int64
	Published    bool
	SelfDestruct bool
	Locked       bool
	LockSalt     string
	LockVerifier string
}

func (q *Queries) GetPage(ctx context.Context, title string) (GetPageRow, error) {
	row := q.db.QueryRowContext(ctx, getPage, title)
	var i GetPageRow
	err := row.Scan(
		&i.Title,
		&i.Text,
		&i.CursorStart,
		&i.CursorEnd,
		&i.Published,
		&i.SelfDestruct,
		&i.Locked,
		&i.LockSalt,
		&i.LockVerifier,
	)
	return i, err
}

const listPublishedPageTitles = `-- name: ListPublishedPageTitles :many
SELECT title
FROM pages
WHERE published = TRUE AND self_destruct = FALSE
ORDER BY title
`

func (q *Queries) ListPublishedPageTitles(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listPublishedPageTitles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var title string
		if err := rows.Scan(&title); err != nil {
			return nil, err
		}
		items = append(items, title)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPage = `-- name: UpsertPage :exec
INSERT INTO pages (
    title,
    text,
    cursor_start,
    cursor_end,
    published,
    self_destruct,
    locked,
    lock_salt,
    lock_verifier
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8,
    ?9
)
ON CONFLICT (title) DO UPDATE SET
    text = excluded.text,
    cursor_start = excluded.cursor_start,
    cursor_end = excluded.cursor_end,
    published = excluded.published,
    self_destruct = excluded.self_destruct,
    locked = excluded.locked,
    lock_salt = excluded.lock_salt,
    lock_verifier = excluded.lock_verifier,
    updated_at = CURRENT_TIMESTAMP
`

type UpsertPageParams struct {
	Title        string
	Text         string
	CursorStart  int64
	CursorEnd    int64
	Published    bool
	SelfDestruct bool
	Locked       bool
	LockSalt     string
	LockVerifier string
}

func (q *Queries) UpsertPage(ctx context.Context, arg UpsertPageParams) error {
	_, err := q.db.ExecContext(ctx, upsertPage,
		arg.Title,
		arg.Text,
		arg.CursorStart,
		arg.CursorEnd,
		arg.Published,
		arg.SelfDestruct,
		arg.Locked,
		arg.LockSalt,
		arg.LockVerifier,
	)
	return err
}
