// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlitedb

import (
	"context"
)

type Querier interface {
	ConsumeE2EESelfDestructPage(ctx context.Context, title string) (ConsumeE2EESelfDestructPageRow, error)
	ConsumeSelfDestructPage(ctx context.Context, title string) (ConsumeSelfDestructPageRow, error)
	ConvertPageToE2EE(ctx context.Context, arg ConvertPageToE2EEParams) (int64, error)
	CreatePage(ctx context.Context, arg CreatePageParams) (int64, error)
	GetPage(ctx context.Context, title string) (GetPageRow, error)
	ListPublishedPageTitles(ctx context.Context) ([]string, error)
	UpsertPage(ctx context.Context, arg UpsertPageParams) error
}

var _ Querier = (*Queries)(nil)
