ALTER TABLE pages ADD COLUMN locked BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE pages ADD COLUMN lock_salt TEXT NOT NULL DEFAULT '';
ALTER TABLE pages ADD COLUMN lock_verifier TEXT NOT NULL DEFAULT '';
